version: "3.9"
services:
  mysql:
    image: mariadb:10.6.4-focal
    container_name: laravel_vue_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        -  mysql_data:/var/lib/mysql
    environment:
        MARIADB_DATABASE: laravelvue
        MARIADB_PASSWORD: 
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: root
  apache:
    image: httpd:alpine3.14
    restart: always
    container_name: laravel_vue_apache
    volumes:
        -  ../laravelVue:/var/www/html
    ports:
    - 8080:80
    depends_on:
      - mysql
    extra_hosts:
      - "laravelvue.com:127.0.0.1"
  php:
    image: composer:2.1.9
    container_name: laravel_vue_php
    command: install
    depends_on:
     - apache
  node:
    image: node:lts-alpine3.14
    container_name: laravel_vue_node
    command: install
    depends_on:
     - apache
volumes:
  mysql_data: {}
