version: "3.9"
services:
  mysql:
    image: mariadb:10.6.4-focal
    container_name: laravel_vue_mysql
    volumes:
        -  mysql_data:/var/lib/mysql
    environment:
        DB_CONNECTION: mysql
        DB_PASSWORD: 
        DB_DATABASE: laravelvue
        DB_USERNAME: root
        DB_PORT: 3306
        DB_HOST: 127.0.0.1
  php:
    image: php:8.0.12-fpm-alpine3.13
    container_name: laravel_vue_php
    depends_on:
      - mysql
  apache:
    image: httpd:alpine3.14
    container_name: laravel_vue_apache
    volumes:
        -  ../laravelVue:/var/www/html
    ports:
    - 8080:80
    depends_on:
      - php
    extra_hosts:
      - "laravelvue.com:127.0.0.1"
volumes:
  mysql_data: {}
